### ISSUE TITLE
Prepare `bpmn-js-color-picker` to be included in camunda modeling

### ISSUE THREAD

**Issue by smbea** [bpmn-io/bpmn-js-color-picker#8]
__What should we do?__

Do some refining and clean up:

**To-Do:**
- [x] (for now) Match UI to the one shown here: https://github.com/camunda/camunda-modeler-design/issues/101
- [x] Generate color icons (via data-URL) based on defined colors (instead of defining it with CSS for each color) (https://github.com/bpmn-io/bpmn-js-color-picker/issues/12)
- [x] Allow colors to be configurable (and therefore customisable by users) (https://github.com/bpmn-io/bpmn-js-color-picker/issues/11)
- [x] Integrate it into the [multi-element context pad](https://github.com/orgs/camunda/projects/9/views/11) (https://github.com/bpmn-io/bpmn-js-color-picker/issues/13)

__Why should we do it?__

Improve the color picker in order to include it in `camunda-bpmn-js`.
Allow color extensibility for bpmn-js users.

**Comment by CatalinaMoisuc** [comment]
@smbea do we already know exactly which version of camunda-bpmn-js will include this feature?

**Comment by smbea** [comment]
Since this hasn't been worked on yet, it won't be included in the next version (for the next Desktop Modeler release). But should be included after that. I'm guessing @barmac may work on this, since he's taking on the multi-element context pad actions

**Comment by christian-konrad** [comment]
As discussed, I decoupled it from the https://github.com/orgs/camunda/projects/9/views/11 epic.

**Comment by nikku** [comment]
Will be fixed via https://github.com/bpmn-io/bpmn-js-color-picker/pull/14.
